package by.gsu.epamlab.webshop.exceptions;

public enum ConstantException {
    ERROR_CAN_NOT_TAKE_CONNECTION,
    GETHASH_METHOD_CRYPTOGRAPHIC_ALGORITHM_GETINSTANCE_IS_NOT_AVAILABLE,
    GETHASH_METHOD_FACTORY_CAN_NOT_GENERATE_HASH

}
